version: 2.1
executors:
  base-jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
  circleci-ubuntu:
    docker:
      - image: cimg/base:2020.01
  trivy:
    docker:
      - image: aquasec/trivy:latest
  helm:
    docker:
      - image: nukengprodservice/helm:latest
  owasp-zap:
    docker:
      - image: owasp/zap2docker-stable:latest

aliases:
  - &mount_workspace
    attach_workspace:
      at: .
  - &restore_gradlew_cache
    restore_cache:
      keys:
        - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &restore_gradle_cache
    restore_cache:
      keys:
        - v1-gradle-cache-{{ checksum "build.gradle" }}
  - &save_dependency_vulnerability_cache
    save_cache:
      key: v1-dependency-cache-{{ checksum "build.gradle" }}
      paths:
        - /home/circleci/.gradle/dependency-check-data/4.0/
  - &restore_dependency_vulnerability_cache
    restore_cache:
      keys:
        - v1-dependency-cache-{{ checksum "build.gradle" }}
  - &only_allowed_branches
    filters:
      branches:
        only:
          - master
          - /dependabot.*/
  - &only_master
    filters:
      branches:
        only:
          - master
  - &only_dependabot
    filters:
      branches:
        only:
          - /dependabot.*/
  - &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - .
  - &credential_context
    context: credentials

jobs:
  build:
    executor: base-jdk8
    description: Install dependencies & Build
    steps:
      - checkout
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: Install Dependencies
          command: |
            ./gradlew build -x test -x checkstyleTest
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - *persist_to_workspace
  test:
    executor: base-jdk8
    description: Unit Test & Code Coverage
    steps:
      - *mount_workspace
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: Run Unit and E2E tests
          command: ./gradlew test
      - store_artifacts:
          path: build/reports/tests/test
          when: always
      - store_test_results:
          path: build/test-results/test
          when: always
      - *persist_to_workspace
  #  This is a generic parameterized gradle task execution job.
  #  At the moment it's being used by Jacoco,Checkstyle and Mutation Test jobs
  gradle_execute_task:
    executor: base-jdk8
    parameters:
      step_name:
        type: string
        default: executing the task
      gradle_task:
        type: string
      artifact_path:
        type: string
    steps:
      - *mount_workspace
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - run:
          name: << parameters.step_name >>
          command: ./gradlew '<< parameters.gradle_task >>'
      - store_artifacts:
          path: << parameters.artifact_path >>
          when: always
  check_dependency_vulnerability:
    executor: base-jdk8
    parameters:
      timeout:
        description: Execution timeout for running the step command
        type: string
        default: 10m
    description: Dependency Vulnerability Check
    steps:
      - *mount_workspace
      - checkout
      - *restore_gradlew_cache
      - *restore_gradle_cache
      - *restore_dependency_vulnerability_cache
      - run:
          name: Perform Dependency Vulnerability Checks
          no_output_timeout: << parameters.timeout >>
          command: ./gradlew dependencyCheckAnalyze
      - *save_dependency_vulnerability_cache
      - store_test_results:
          path: build/reports/dependency-vulnerabilities
          when: always
      - store_artifacts:
          path: build/reports/dependency-vulnerabilities
          when: always
  image_build_scan_push:
    docker:
      - image: docker:stable-git
    steps:
      - *mount_workspace
      - setup_remote_docker
      - run:
          name: Docker Image build
          command: |
            pwd
            echo "files in the dir"
            ls -la
            ./.circleci/scripts/docker-build.sh build_image
      - run:
          name: Scan Image Vulnerability
          command: ./.circleci/scripts/vulnerability-checks.sh
      - run:
          name: Push Image
          command: ./.circleci/scripts/docker-build.sh push_image

  build_and_push_image:
    description: Build Docker Image & Push
    executor: base-jdk8
    steps:
      - *mount_workspace
      - setup_remote_docker
      - run:
          name: Docker Image build and push
          command: .circleci/scripts/docker-build.sh
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - version.txt
  check_image_vulnerability:
    description: Use Trivy to check the final docker image vulnerabilities before deployment
    executor: trivy
    steps:
      - checkout
      - run:
          name: Trivy Image Vulnerability Check
          command: |
            apk add --no-cache bash
            /root/project/.circleci/scripts/vulnerability-checks.sh
      - store_artifacts:
          path: reports
          when: always
  merge_pr:
    executor: base-jdk8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
      - run:
          name: Merging Pull request automatically
          command: |
            #!/usr/bin/env bash
            set -euo pipefail
            echo "mergin branch ${CIRCLE_BRANCH} to master ...."
            echo "set remote traking"
            git fetch origin
            echo "checkout a new local branch"
            git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
            git merge master
            git checkout master
            echo "merging the branch to master"
            git merge --no-ff ${CIRCLE_BRANCH}
            git push origin master
            echo "completes..."
  helm_deploy:
    executor: helm
    parameters:
      release:
        type: string
    steps:
      - *mount_workspace
      - checkout
      - run:
          name: aws eks config update
          command: aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${EKS_CLUSTER_NAME}
      - run:
          name: helm release
          command: |
            RELEASE_NAME="<< parameters.release >>" \
            EKS_NAMESPACE="${EKS_NAMESPACE}" \
            ./.circleci/scripts/helm-deploy.sh
  health_check:
    executor: circleci-ubuntu
    steps:
      - checkout
      - run:
          name: Perform API Health Check
          command: ./.circleci/scripts/health-check.sh
  penetration_test:
    executor: owasp-zap
    steps:
      - run:
          name: Perform Penetration Test
          command: |
            cd ../../../zap/
            echo "Running from containers home zap directory..."
            mkdir wrk && zap-baseline.py -t "${HEALTH_ENDPOINT}" -g gen.conf -r penetration-test-report.html || :
            echo "Moving Pen Test report to the circleci job working dir.."
            mv wrk/* ../home/zap/project/
      - store_artifacts:
          path: .

workflows:
  version: 2.1
  workflow-all-jobs:
    jobs:
      - build:
          <<: *only_allowed_branches
          name: Build
      - image_build_scan_push:
          requires:
            - Build
